// <auto-generated />

#nullable disable

namespace EvolutionaryArchitecture.LeaseBuyArch.Vehicles.Data.Database.Migrations
{
    using System;
    using EvolutionaryArchitecture.LeaseBuyArch.Vehicles.Data.Database;
    using Microsoft.EntityFrameworkCore;
    using Microsoft.EntityFrameworkCore.Infrastructure;
    using Microsoft.EntityFrameworkCore.Migrations;
    using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

    [DbContext(typeof(VehiclesPersistence))]
    [Migration("20230503180339_Create_Vehicles_Table")]
    partial class Create_Vehicles_Table
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Vehicles")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EvolutionaryArchitecture.LeaseBuyArch.Vehicles.Data.Vehicle", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                b.Property<string>("Make").IsRequired().HasColumnType("text");
                b.Property<string>("Model").IsRequired().HasColumnType("text");
                b.Property<int>("Year").HasColumnType("integer");
                b.Property<decimal>("Msrp").HasColumnType("numeric");
                b.Property<decimal>("ResidualPercentageAt36Months").HasColumnType("numeric");
                b.Property<string>("Status").IsRequired().HasColumnType("text");
                b.HasKey("Id");
                b.ToTable("Vehicles", "Vehicles");
            });
#pragma warning restore 612, 618
        }
    }
}
