// <auto-generated />
using System;
using System.Diagnostics.CodeAnalysis;
using EvolutionaryArchitecture.LeaseBuyArch.Leasing.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EvolutionaryArchitecture.LeaseBuyArch.Leasing.Infrastructure.Database.Migrations
{
    [DbContext(typeof(LeasingPersistence))]
    [ExcludeFromCodeCoverage]
    partial class LeasingPersistenceModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
            modelBuilder.HasDefaultSchema("Leasing").HasAnnotation("ProductVersion", "10.0.8").HasAnnotation("Relational:MaxIdentifierLength", 63);
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);
            modelBuilder.Entity("EvolutionaryArchitecture.LeaseBuyArch.Leasing.Core.Lease", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                b.Property<int>("AnnualMileageLimit").HasColumnType("integer");
                b.Property<Guid>("CustomerId").HasColumnType("uuid");
                b.Property<decimal>("MoneyFactor").HasColumnType("numeric");
                b.Property<decimal>("MonthlyPayment").HasColumnType("numeric");
                b.Property<DateTimeOffset>("PreparedAt").HasColumnType("timestamp with time zone");
                b.Property<decimal>("ResidualPercentage").HasColumnType("numeric");
                b.Property<DateTimeOffset?>("SignedAt").HasColumnType("timestamp with time zone");
                b.Property<int>("TermMonths").HasColumnType("integer");
                b.Property<Guid>("VehicleId").HasColumnType("uuid");
                b.Property<decimal>("VehicleMsrp").HasColumnType("numeric");
                b.HasKey("Id");
                b.ToTable("Leases", "Leasing");
            });
        }
    }
}
