// <auto-generated />
using System;
using System.Diagnostics.CodeAnalysis;
using EvolutionaryArchitecture.LeaseBuyArch.Vehicles.DataAccess.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EvolutionaryArchitecture.LeaseBuyArch.Vehicles.DataAccess.Database.Migrations
{
    [DbContext(typeof(VehiclesPersistence))]
    [ExcludeFromCodeCoverage]
    partial class VehiclesPersistenceModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
            modelBuilder.HasDefaultSchema("Vehicles").HasAnnotation("ProductVersion", "10.0.8").HasAnnotation("Relational:MaxIdentifierLength", 63);
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);
            modelBuilder.Entity("EvolutionaryArchitecture.LeaseBuyArch.Vehicles.DataAccess.Vehicle", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                b.Property<string>("Make").IsRequired().HasColumnType("text");
                b.Property<string>("Model").IsRequired().HasColumnType("text");
                b.Property<decimal>("Msrp").HasColumnType("numeric");
                b.Property<decimal>("ResidualPercentageAt36Months").HasColumnType("numeric");
                b.Property<string>("Status").IsRequired().HasColumnType("text");
                b.Property<int>("Year").HasColumnType("integer");
                b.HasKey("Id");
                b.ToTable("Vehicles", "Vehicles");
            });
        }
    }
}
