// <auto-generated />

#nullable disable

namespace EvolutionaryArchitecture.LeaseBuyArch.Leasing.Data.Database.Migrations
{
    using System;
    using EvolutionaryArchitecture.LeaseBuyArch.Leasing.Data.Database;
    using Microsoft.EntityFrameworkCore;
    using Microsoft.EntityFrameworkCore.Infrastructure;
    using Microsoft.EntityFrameworkCore.Migrations;
    using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

    [DbContext(typeof(LeasingPersistence))]
    [Migration("20230503180334_Create_Leases_Table")]
    partial class Create_Leases_Table
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Leasing")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EvolutionaryArchitecture.LeaseBuyArch.Leasing.Data.Lease", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                b.Property<Guid>("CustomerId").HasColumnType("uuid");
                b.Property<Guid>("VehicleId").HasColumnType("uuid");
                b.Property<decimal>("VehicleMsrp").HasColumnType("numeric");
                b.Property<decimal>("ResidualPercentage").HasColumnType("numeric");
                b.Property<decimal>("MoneyFactor").HasColumnType("numeric");
                b.Property<int>("TermMonths").HasColumnType("integer");
                b.Property<int>("AnnualMileageLimit").HasColumnType("integer");
                b.Property<decimal>("MonthlyPayment").HasColumnType("numeric");
                b.Property<DateTimeOffset>("PreparedAt").HasColumnType("timestamp with time zone");
                b.Property<DateTimeOffset?>("SignedAt").HasColumnType("timestamp with time zone");
                b.HasKey("Id");
                b.ToTable("Leases", "Leasing");
            });
#pragma warning restore 612, 618
        }
    }
}
