// <auto-generated />

#nullable disable

namespace EvolutionaryArchitecture.LeaseBuyArch.Purchasing.Data.Database.Migrations
{
    using System;
    using EvolutionaryArchitecture.LeaseBuyArch.Purchasing.Data.Database;
    using Microsoft.EntityFrameworkCore;
    using Microsoft.EntityFrameworkCore.Infrastructure;
    using Microsoft.EntityFrameworkCore.Migrations;
    using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

    [DbContext(typeof(PurchasingPersistence))]
    [Migration("20230503180338_Create_Purchases_Table")]
    partial class Create_Purchases_Table
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Purchasing")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EvolutionaryArchitecture.LeaseBuyArch.Purchasing.Data.Purchase", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                b.Property<Guid>("CustomerId").HasColumnType("uuid");
                b.Property<Guid>("VehicleId").HasColumnType("uuid");
                b.Property<decimal>("VehicleMsrp").HasColumnType("numeric");
                b.Property<decimal>("DownPayment").HasColumnType("numeric");
                b.Property<decimal>("Apr").HasColumnType("numeric");
                b.Property<int>("TermMonths").HasColumnType("integer");
                b.Property<decimal>("MonthlyPayment").HasColumnType("numeric");
                b.Property<DateTimeOffset>("PreparedAt").HasColumnType("timestamp with time zone");
                b.Property<DateTimeOffset?>("CompletedAt").HasColumnType("timestamp with time zone");
                b.HasKey("Id");
                b.ToTable("Purchases", "Purchasing");
            });
#pragma warning restore 612, 618
        }
    }
}
