// <auto-generated />
using System;
using System.Diagnostics.CodeAnalysis;
using EvolutionaryArchitecture.LeaseBuyArch.Purchasing.DataAccess.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EvolutionaryArchitecture.LeaseBuyArch.Purchasing.DataAccess.Database.Migrations
{
    [DbContext(typeof(PurchasingPersistence))]
    [ExcludeFromCodeCoverage]
    partial class PurchasingPersistenceModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
            modelBuilder.HasDefaultSchema("Purchasing").HasAnnotation("ProductVersion", "10.0.8").HasAnnotation("Relational:MaxIdentifierLength", 63);
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);
            modelBuilder.Entity("EvolutionaryArchitecture.LeaseBuyArch.Purchasing.DataAccess.Purchase", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                b.Property<decimal>("Apr").HasColumnType("numeric");
                b.Property<DateTimeOffset?>("CompletedAt").HasColumnType("timestamp with time zone");
                b.Property<Guid>("CustomerId").HasColumnType("uuid");
                b.Property<decimal>("DownPayment").HasColumnType("numeric");
                b.Property<decimal>("MonthlyPayment").HasColumnType("numeric");
                b.Property<DateTimeOffset>("PreparedAt").HasColumnType("timestamp with time zone");
                b.Property<int>("TermMonths").HasColumnType("integer");
                b.Property<Guid>("VehicleId").HasColumnType("uuid");
                b.Property<decimal>("VehicleMsrp").HasColumnType("numeric");
                b.HasKey("Id");
                b.ToTable("Purchases", "Purchasing");
            });
        }
    }
}
